[package]
name = "neri-player-desktop"
version = "1.0.0"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["macos-private-api"] }
tauri-plugin-opener = "2.5.4"
tauri-plugin-store = "2"
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", features = ["json", "cookies", "stream"] }
cpal = "0.15"
symphonia = { version = "0.5", features = ["aac", "flac", "isomp4", "mp3", "vorbis", "wav", "pcm", "adpcm"] }
lofty = "0.21"
md-5 = "0.10"
aes = "0.8"
cbc = "0.1"
ecb = "0.1"
rsa = "0.9"
sha1 = "0.10"
hmac = "0.12"
hex = "0.4"
base64 = "0.22"
url = "2"
rand = "0.8"
chrono = "0.4"
thiserror = "2"
parking_lot = "0.12"
walkdir = "2"
urlencoding = "2"
regex = "1"
sha2 = "0.10"
uuid = { version = "1", features = ["v4"] }
whoami = "1"
log = "0.4"
dirs-next = "2"
prost = "0.13"
flate2 = "1"
souvlaki = "0.7"
raw-window-handle = "0.6"
tokio-tungstenite = { version = "0.24", features = ["native-tls"] }
futures-util = "0.3"
tauri-plugin-clipboard-manager = "2.3.2"
tempfile = "3"
image = { version = "0.25", default-features = false, features = ["gif", "jpeg", "png", "webp"] }
keyring = { version = "3", default-features = false, features = ["apple-native", "windows-native", "sync-secret-service"] }
tauri-plugin-log = "2.9.0"

[profile.dev.package.symphonia]
opt-level = 2

[profile.dev.package.symphonia-core]
opt-level = 2

[profile.dev.package.symphonia-bundle-mp3]
opt-level = 2

[profile.dev.package.symphonia-codec-aac]
opt-level = 2

[profile.dev.package.symphonia-codec-vorbis]
opt-level = 2

[profile.dev.package.symphonia-format-isomp4]
opt-level = 2

[profile.dev.package.symphonia-format-ogg]
opt-level = 2
